apiVersion: v1
kind: Service
metadata:
  name: onoff-detection
  namespace: cody
  labels:
    app: onoff-detection
    mindsett.type: analysis
    mindsett.status: development
    mindsett.owner: cody
    mindsett.deployment: mae
spec:
  clusterIP: None
  selector:
    app: onoff-detection

